version: '2'
services:
  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    ports:
      - '127.0.0.1:3000:3000'
#    volumes:
#      - grafana-storage:/var/lib/grafana
#      - ./grafana-provisioning/:/etc/grafana/provisioning
#    environment:
#      - GF_AUTH_ANONYMOUS_ENABLED=true
#      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
