on: release
name: Publish
jobs:
  publish-to-pypi:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: publish-to-pypi
      uses: mariamrf/py-package-publish-action@master
      env:
        BRANCH: master
        PYTHON_VERSION: 3.7.0
        TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
        TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
    - name: publish-to-conda
      uses: m0nhawk/conda-package-publish-action@master
      env:
        ANACONDA_PASSWORD: ${{ secrets.ANACONDA_PASSWORD }}
        ANACONDA_USERNAME: ${{ secrets.ANACONDA_USERNAME }}
